@startuml

' !include theme.puml
hide circle

interface Interpret< T > << interface >> {
    + translate(string) -> T
}

class MusicInterpret< T = Score > implements Interpret

class MusicIntInfo {
    + key : KeySignature
    + first_note : Note
    + time_signature : TimeSignature
    + tempo : Tempo
}

class Context {
    + note: Note
    + stave_notes: Vec<Note>
    + stack: Vec<Note>
}

class Scale {
    + advance(pitch)
    + recede(pitch)
}

MusicInterpret -down-> MusicIntInfo
MusicInterpret .down.> Context : <<use>>
Scale -up-> KeySignature
Context -up-> Scale

@enduml
