@startuml
hide circle

class RuleSet {
    + select(s : <color:green>String</color>) -> <color:purple>Rule?</color>
}

class Rule {
    + left : <color:green>String</color>
    + right : <color:green>String</color>
    + p : <color:blue>float</color>
    + matches(s : <color:green>String</color>) -> <color:purple>bool</color>
}

RuleSet *-right- "*" Rule : "          "

@enduml
